# NUMPY PRACTICE
### # NumPy Practice for Data Analysis and Machine Learning

In [1]:
import numpy as np
arr = np.array([[2,3,4],
                [2,3,4]
               ])
arr

array([[2, 3, 4],
       [2, 3, 4]])

## 1.Array Shape

In [4]:
np.shape(arr)

(2, 3)

## 2. Axis Operations

In [6]:
np.sum(arr, axis=0)  # axis = 0 → column wise operation

array([4, 6, 8])

In [7]:
np.sum(arr,axis = 1) # axis = 1 → row wise operation

array([9, 9])

# 3.Broadcasting

In [8]:
# Broadcasting allows NumPy to perform operations
# on arrays with different shapes automatically.
a = np.array([[2,3,4],
              [1,2,3]
             ])
b = np.array([10,20,30])   
a+b

array([[12, 23, 34],
       [11, 22, 33]])

In [9]:
a = np.array([[2,3,4],
              [1,2,3]
             ])
b = np.array([10,20]).reshape(2,1)
a+b    #this doesnt work as b cant be broadcasts because its not compatible so we uses .reshape so that it will work

array([[12, 13, 14],
       [21, 22, 23]])

In [13]:
#Broadcasting Example Using Ones Array
a = np.ones((3,1))
b = np.ones((1,4))
a + b

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

# 4.Boolean Masking

In [7]:
# Boolean masking filters elements based on condition
a = np.array([10,20,30,45,30,20])
a >  30
a[a>30]
a[a%2 ==0]

array([10, 20, 30, 30, 20])

# 5. Reshaping Arrays

In [9]:
a = np.array([10,20,30,45,30,20])
a.reshape(-1,2)

array([[10, 20],
       [30, 45],
       [30, 20]])

# 6. Flatten vs Ravel

In [34]:
a = np.array([[2,3,4],[1,2,3]])
b = a.flatten()
b[1] = 100
a  #flatten only copies not record changes

array([[2, 3, 4],
       [1, 2, 3]])

In [35]:
a = np.array([[2,3,4],[1,2,3]])
b = a.ravel()
b[1] = 100
a   #ravel is a view...memory efficient, record changes

array([[  2, 100,   4],
       [  1,   2,   3]])

# 7. Stacking Arrays

In [36]:

a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b,))


array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.concatenate((a,b))  #same as hstack

array([1, 2, 3, 4, 5, 6])

# 8. Column Vector Reshaping

In [11]:
#reshape as column vector meaning only 1 column 
a = np.array([[2,3,4],
              [1,2,3]
             ])
a.reshape(-1,1)
# a.reshape(6,1) 

array([[2],
       [3],
       [4],
       [1],
       [2],
       [3]])

# 9. Dot Product (Matrix Multiplication)

In [2]:
import numpy as np
features = np.array([[1,2],[3,4],[5,6]])
weights = np.array([0.5,1.0])
np.dot(features, weights)

array([2.5, 5.5, 8.5])

# 10. Fancy Indexing

In [15]:
#Fancy indexing allows selecting multiple elements using index list.
a = np.array([10,20,30,40,50])
a[[0,2,4]]

array([10, 30])

# 11. Random Number Generator

In [19]:
np.random.rand(3,3)
np.random.randint(1,100,5)
np.random.normal(0,1,10)

array([ 0.19920847,  0.67777281, -1.02491676, -0.04542318, -1.07559082,
       -1.25074985,  1.21352878, -0.74488744,  0.16918992, -1.96345507])

# 12. Statistic functions

In [20]:
a = np.array([10,20,30,40,50])

np.mean(a)
np.median(a)
np.std(a)
np.max(a)
np.min(a)

np.int64(10)

# 13. Sorting

In [23]:
a = np.array([30,10,50,20])
np.sort(a) 
np.argsort(a) # returns the index of sorting order

array([1, 3, 0, 2])